# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sesion12-01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'

  # Pods for Sesion12-01

end
